data:
  dataset_name: "lmdc_3000_2bar_4res"
  part_1: "Melody"
  part_2: "Bass"
  repr_1: "onset_roll"
  repr_2: "onset_roll"
  context_len: 33

splits:
  train: 0.8
  val: 0.1
  test: 0.1

model:
  enc_d_model: 192
  enc_n_layer: 10
  enc_n_head: 4
  enc_d_ff: 480
  enc_dropout: 0.1
  dec_d_model: 192
  dec_n_layer: 8
  dec_n_head: 3
  dec_d_ff: 480
  dec_dropout: 0.1
  d_embed: 192
  d_vae_latent: 48
  emb_dropout: 0.1

kl_max_beta: 1.0
free_bit_lambda:  0.25

sequence_len: 32
resolution: 4
n_epochs: 3
batch_size: 8
lr: 1e-4
weight_decay: 0.0001
n_eval_iters: 3
seed: 13
wandb: False
bento: False
checkpoints: False
val_interval: 50
