data:
  dataset_name: "lmdc_17243_2bar_4res"
  part_1: "Bass"
  part_2: "Drums"
  repr_1: "onset_roll"
  repr_2: "drum_roll"

splits:
  train: 0.8
  val: 0.1
  test: 0.1

model:
  n_embed: 128
  n_layer: 3
  n_head: 4
  d_ff: 1024
  dropout: 0.5

sequence_len: 32
resolution: 4
loss_fn: "cross-entropy"
loss_reduction: 'mean'
clip_gradients: False
num_epochs: 5
batch_size: 8
lr: 1e-4
weight_decay: 0.0001
n_eval_iters: 25
seed: 13
wandb: True
bento: True
checkpoints: True
