dataset:
  dataset_name: "lmdc_10000_2bar_4res"
  part: "Melody"
  representation: "onset_roll"
  context_len: 16
model:
  x_dim: 512
  h_dim: 256
  z_dim: 128
  dropout: .5
  y_dim: 32
loss_fn: "cross-entropy"
loss_reduction: 'mean'
clip_gradients: False
num_epochs: 5
batch_size: 512
lr: 1e-3
wandb: True
