dataset:
  dataset_name: "lmdc_17243_2bar_4res"
  part: "Melody"
  representation: "onset_roll"
  context_len: 31

model:
  n_embed: 96
  n_head: 2
  n_layer: 3
  dropout: 0.2

sequence_len: 32
resolution: 4
loss_fn: "cross-entropy"
loss_reduction: 'mean'
clip_gradients: False
num_epochs: 5
batch_size: 128
lr: 1e-3
n_eval_iters: 20
n_eval_seqs: 100
splits:
  train: 0.8
  val: 0.1
  test: 0.1
seed: 13
wandb: False
save_checkpoints: False
bento: False
