data:
  dataset_name: "lmdc_chroma_3000_2bar_4res"
  part: "Harmony"
  representation: "onset_chroma"
  block_size: 1

model:
  n_embed: 144
  n_layer: 4
  n_head: 3
  dropout: 0.4

splits:
  train: 0.9
  val: 0.05
  test: 0.05

seed: 13
sequence_len: 32
n_epochs: 3
batch_size: 128

lr: 1e-4
loss_fn: "cross-entropy"
loss_reduction: "mean"
clip_gradients: False
weight_decay: 0

wandb: False
bento: False
checkpoints: True

n_eval_iters: 20
n_eval_seqs: 10
eval_interval: 2500
