data:
  dataset_name: "lmdc_3000_2bar_4res"
  part_1: "Bass"
  part_2: "Melody"
  repr_1: "hits"
  repr_2: "hits"
  context_len: 31

model:
  enc_n_embed: 96
  enc_n_layer: 3
  enc_n_head: 2
  enc_dropout: 0.1
  dec_n_embed: 96
  dec_n_layer: 3
  dec_n_head: 2
  dec_dropout: 0.2

splits:
  train: 0.8
  val: 0.1
  test: 0.1

seed: 13
sequence_len: 32
n_epochs: 5
batch_size: 64

lr: 3e-4
loss_fn: "cross-entropy"
loss_reduction: "mean"
clip_gradients: False
weight_decay: 0

n_eval_iters: 1
wandb: False
bento: False
checkpoints: True

val_interval: 100
