data:
  dataset_name: "lmdc_17243_2bar_4res"
  part_1: "Melody"
  part_2: "Bass"
  repr_1: "hits"
  repr_2: "hits"
  block_size: 1

model:
  enc_n_embed: 144
  enc_n_layer: 4
  enc_n_head: 3
  enc_dropout: 0.4
  dec_n_embed: 144
  dec_n_layer: 4
  dec_n_head: 3
  dec_dropout: 0.4

splits:
  train: 0.9
  val: 0.05
  test: 0.05

seed: 13
sequence_len: 32
n_epochs: 5
batch_size: 128

lr: 1e-5
loss_fn: "cross-entropy"
loss_reduction: "mean"
clip_gradients: False
weight_decay: 0

wandb: False
bento: False
checkpoints: True

n_eval_iters: 100
n_eval_seqs: 50
eval_interval: 2500
