data:
  dataset_name: "lmdc_3000_2bar_4res"
  part: "Melody"
  representation: "hits"
  context_len: 31

splits:
  train: 0.8
  val: 0.1
  test: 0.1

model:
  n_embed: 96
  n_layer: 3
  n_head: 2
  dropout: 0.2

seed: 13
sequence_len: 32
n_epochs: 5
batch_size: 64

lr: 3e-4
loss_fn: "cross-entropy"
loss_reduction: "mean"
clip_gradients: True
weight_decay: 0

n_eval_iters: 10
wandb: False
bento: False
checkpoints: False

val_interval: 50
