dataset:
  dataset_name: "lmd_clean_1000_2bar_24res"
  part_1: "Bass"
  part_2: "Drums"
  repr_1: "pattern"
  repr_2: "pattern"
model:
  x_dim: 32
  h_dim: 8
  z_dim: 2
  conditional: True
  y_dim: 32
loss_fn: "bce"
loss_reduction: 'sum'
clip_gradients: True
num_epochs: 10
batch_size: 256
lr: 1e-4
