dataset:
  dataset_name: "lmdc_3000_1bar_4res"
  part_1: "Guitar"
  part_2: "Bass"
  repr_1: "onset_roll"
  repr_2: "onset_roll"
model:
  x_dim: 2048
  h_dims:
    - 256
  z_dim: 30
  conditional: True
  y_dim: 2048
loss_fn: "bce-logits"
loss_reduction: 'sum'
clip_gradients: True
num_epochs: 5
batch_size: 256
lr: 1e-4
