data:
  dataset_name: "lmdc_500_2bar_4res"
  part_1: "Melody"
  part_2: "Bass"
  repr_1: "onset_roll"
  repr_2: "onset_roll"
  context_len: 32

model:
  vocab_size: 131
  n_embed: 32
  encoder_params:
    n_layer: 3
    n_head: 2
    d_ff: 512
    dropout: 0.2
  decoder_params:
    n_layer: 3
    n_head: 2
    d_ff: 512
    dropout: 0.2

sequence_len: 32
resolution: 4
loss_fn: "cross-entropy"
loss_reduction: 'mean'
clip_gradients: False
num_epochs: 4
batch_size: 32
lr: 1e-3
n_eval_iters: 20
n_eval_seqs: 20
splits:
  train: 0.8
  val: 0.1
  test: 0.1
seed: 13
wandb: False
bento: False
save_checkpoints: False
