dataset:
  dataset_name: "lmdc_10000_2bar_4res"
  part: "Melody"
  representation: "onset_roll"
  context_len: 16
model:
  vocab_size: 130
  n_embed: 144
  n_head: 4
  n_layer: 4
  dropout: 0.3
loss_fn: "cross-entropy"
loss_reduction: 'mean'
clip_gradients: False
num_epochs: 15
batch_size: 256
lr: 3e-4
wandb: True
eval_iters: 30
