dataset:
  dataset_name: "lmdc_10000_2bar_4res"
  part: "Melody"
  representation: "onset_roll"
  context_len: 16
model:
  vocab_size: 130
  n_embed: 32
loss_fn: "cross-entropy"
loss_reduction: 'mean'
clip_gradients: False
num_epochs: 10
batch_size: 512
lr: 1e-3
wandb: False
eval_iters: 50
