data:
  dataset_name: "lmdc_500_2bar_4res"
  part_1: "Drums"
  part_2: "Bass"
  repr_1: "drum_roll"
  repr_2: "onset_roll"
  context_len: 32

model:
  n_embed: 64
  n_layer: 2
  n_head: 2
  d_ff: 512
  dropout: 0.2

sequence_len: 32
resolution: 4
loss_fn: "cross-entropy"
loss_reduction: 'mean'
clip_gradients: False
num_epochs: 3
batch_size: 48
lr: 1e-3
n_eval_iters: 20
n_eval_seqs: 20
splits:
  train: 0.8
  val: 0.1
  test: 0.1
seed: 13
wandb: False
bento: False
save_checkpoints: False
